In [18]:
import numpy as np
from numpy import linspace, random

In [54]:
def generate_points(low=3, hight=10, dubs=False):
    """Генерация 2D точек от low до hight штук"""
    for n in range(low, hight+1, 1):
        n_ = n//2
        x_upper = linspace(1, 0, n_, endpoint=dubs)
        x_lower = linspace(0, 1, n_, endpoint=True)
        y_upper, y_lower = random.randn(len(x_upper)), random.randn(len(x_lower))
        x = np.concatenate([x_upper, x_lower], axis=0)
        y = np.concatenate([y_upper, y_lower], axis=0)
        yield np.vstack([x, y]).T

In [55]:
for points in generate_points():
    print(points)
    print()

[[1.         0.98259561]
 [0.         0.88865041]]

[[ 1.          0.08173914]
 [ 0.5         1.14865547]
 [ 0.          0.19217928]
 [ 1.         -0.26804109]]

[[ 1.         -0.07538025]
 [ 0.5        -0.56020348]
 [ 0.          1.01768422]
 [ 1.         -0.65688785]]

[[ 1.          0.33692757]
 [ 0.66666667  0.23267409]
 [ 0.33333333  1.40710394]
 [ 0.         -0.40612863]
 [ 0.5         2.2385974 ]
 [ 1.          0.86245794]]

[[ 1.          1.25643526]
 [ 0.66666667 -1.10892732]
 [ 0.33333333 -0.0897254 ]
 [ 0.         -2.51164585]
 [ 0.5         0.10764821]
 [ 1.          1.09060277]]

[[ 1.          0.641106  ]
 [ 0.75        0.04896941]
 [ 0.5         0.24745182]
 [ 0.25       -0.18160225]
 [ 0.          1.33173158]
 [ 0.33333333 -0.82067419]
 [ 0.66666667 -1.60375801]
 [ 1.         -0.66622426]]

[[ 1.         -0.61909713]
 [ 0.75       -0.34043146]
 [ 0.5        -0.69669974]
 [ 0.25        0.08694749]
 [ 0.          0.63296145]
 [ 0.33333333 -0.82702726]
 [ 0.66666667  0.297